### PR TITLE
Update Detekt to 1.23.4

### PR DESCRIPTION
**Pull request by AzimMuradov**
Should fix issues in #374 automatic PR

### CODE REVIEW

**Comment by AzimMuradov** [comment]
Changes:

- Update Detekt to 1.23.4
  - Update detekt config

  Updated according to the detekt README (https://github.com/detekt/detekt?tab=readme-ov-file#with-gradle).

  - Add `formatting` detekt plugin
  
  In the newest detekt versions, the `formatting` rule set should be added separately via `detektPlugins` mechanism.
  
  From https://github.com/detekt/detekt?tab=readme-ov-file#adding-more-rule-sets:
  
  > detekt itself provides a wrapper over [ktlint](https://github.com/pinterest/ktlint) as the formatting rule set which can be easily added to the Gradle configuration:
  >
  > ```kts
  > dependencies {
  >     detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:[version]")
  > }
  > ```

  - Clean up the code to pass the updated checks

- Reorganize build.gradle.kts

I hope this change would make the build script more readable and generally nice to config.

- Set up indentation level to 2 spaces

This style guide is already present in the project, so I decided to explicitly describe it in the .editorconfig and detekt.yml.

**Comment by AzimMuradov** [comment]
BTW, why does the build script use `spotless` and `detekt` at the same time? I thought the `detekt` would be more than enough.

**Comment by AzimMuradov** [comment]
Also, I could filter out detekt tasks on `...Test` source sets if it's needed.

It's as simple as changing

```kts
tasks {

    // ...

    afterEvaluate {
        check {
            dependsOn(withType<Detekt>())
        }
    }
}
```

to

```kts
tasks {

    // ...

    afterEvaluate {
        check {
            dependsOn(withType<Detekt>().filterNot { it.name.contains("test", ignoreCase = true) })
        }
    }
}
```

**Comment by oshai** [comment]
> BTW, why does the build script use `spotless` and `detekt` at the same time? I think the `detekt` would be more than enough.

If I remember correctly we started with detekt and now use spotless (don't remember why I changed it...). So I am not sure we need detekt at all.

**Comment by AzimMuradov** [comment]
> > BTW, why does the build script use `spotless` and `detekt` at the same time? I think the `detekt` would be more than enough.
> 
> If I remember correctly we started with detekt and now use spotless (don't remember why I changed it...). So I am not sure we need detekt at all.

As far as I know, detekt is a full blown static analysis tool while spotless is more like a formatter/code style checker.

If you want, I can remove detekt from the config. If so, should I just rename this pr, or should I close it, and open the new one?

**Comment by AzimMuradov** [comment]
The reason I created this PR is because old `detekt` blocks the addition of the `wasmJs` target. So, if you currently don't want to remove `detekt`, we can think about it later and I'd just update it version for now. If you don't currently want to remove `detekt` we can think about that later and for now I'll just update it's version.

**Comment by oshai** [comment]
Let's stay only with spotless and remove detekt.

**Pull request closed without merging**
