### PR TITLE
Support arguments where possible for Logback and Slf4j

### PR DESCRIPTION
**Pull request by sigmanil**
Proposal for https://github.com/oshai/kotlin-logging/issues/457

Added arguments array and passed it to underlying loggers where possible, not all loggers seem to support it. (Array instead of the initially proposed Set, because that is the datatype used by the underlying loggers.)

### CODE REVIEW

**Comment by oshai** [comment]
Thanks for the PR! Generally LGTM. Is it possible to add a unit test for your use case?

**Comment by sigmanil** [comment]
Something like this? https://github.com/oshai/kotlin-logging/pull/458/commits/d57c87173b40efb32c0eb38fa093b785e16462a7

**Comment by sigmanil** [comment]
Noticed that the previous commit failed on formatting (spotless checks). Fixed that now.

**Comment by oshai** [comment]
Thanks! will be released in 7.0.1.

**Pull request merged**
