### PR TITLE
Upgrading Gradle to 8.X

### LINKED ISSUE #288: Upgrade to Gradle 8.0
Creating a task to track this effort

https://docs.gradle.org/8.0/release-notes.html

@oshai Feel free to assign it to me :)

### PR DESCRIPTION
**Pull request by severn-everett**
Upgraded Gradle to 8.7; Upgraded Android plugin to 8.2.2; Upgraded Kotlin Coroutines version to 1.8.0; Enabled cross-platform compatibility for Spotless plugin; Silencing some compiler warnings

Fixes #288

### CODE REVIEW

**Comment by severn-everett** [comment]
@oshai is using Java 11 a requirement for this project? If not, the build machines need to be re-configured to use Java 17 or (preferably) Java 21.

**Comment by oshai** [comment]
I think we can upgrade that.

**Comment by severn-everett** [comment]
Has there been any update on upgrading the CI machines to use a newer version of Java?

**Comment by oshai** [comment]
Would you like to add that to the pull request?

**Comment by severn-everett** [comment]
Apologies, I'm not familiar with Github workflows and didn't realize that the configuration for them is part of the project. I'll take a look at what needs to be modified.

**Comment by oshai** [comment]
Thanks!

**Pull request merged**
