### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sksamuel**
Added https://github.com/grindrllc

### CODE REVIEW

**Comment by oshai** [comment]
Hi, where is kotlin-logging used in https://github.com/grindrllc?

**Comment by sksamuel** [comment]
internal repos. If you only want open source links, then we can close this sorry !

**Comment by oshai** [comment]
It doesn't have to be open source only, but it have to be stated some where that kotlin-logging is used.

**Comment by sksamuel** [comment]
Ok makes sense. Sorry for the confusion.

**Pull request closed without merging**
